### ISSUE TITLE
Good but...

### ISSUE THREAD

**Issue by TBDeveloper01** [smallkingdev-pm-pl/AlwaysDay#1]
The plugin is good but I would like more if the worlds could be configured 
Example:
World1: night 
World2: sunrise
World3: day
World4: default

If you add that I would be very happy

**Comment by SmallkingDev** [comment]
the initial idea of ​​the system was just to be aimed at being a time blocker, thus leaving the day always for the customer, but after a few days I thought of maybe changing the functionality system to block the client time according to the time that was set in the world using the time command

**Comment by TBDeveloper01** [comment]
Yes, your idea is good
